# .github/workflows/gcp-push.yml
name: Push to GCP

on:
  push:
    branches: [ main ]
    paths:
      - 'containers/**'

jobs:
  push-to-gcp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_URL }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Configure GCP Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push
        run: |
          docker build -t ${{ secrets.HARBOR_URL }}/library/app:${{ github.sha }} .
          docker push ${{ secrets.HARBOR_URL }}/library/app:${{ github.sha }}
