# monitoring/alert_policies.yaml
apiVersion: monitoring.googleapis.com/v1
kind: AlertPolicy
metadata:
  name: high-nat-usage
spec:
  displayName: "High NAT Gateway Usage"
  documentation:
    content: "Alert triggered when NAT gateway usage exceeds threshold"
  conditions:
    - displayName: "NAT Gateway Usage > 80%"
      conditionThreshold:
        filter: "metric.type=\"compute.googleapis.com/nat/sent_bytes_count\""
        aggregations:
          - alignmentPeriod: 300s
            perSeriesAligner: ALIGN_RATE
        comparison: COMPARISON_GT
        thresholdValue: 80
        duration: 300s
  alertStrategy:
    autoClose: 1800s
  combiner: OR
  enabled: true
  notificationChannels:
    - "projects/PROJECT_ID/notificationChannels/CHANNEL_ID"
