# pyproject.toml
[tool.poetry]
name = "ghas-langchain-security"
version = "0.1.0"
description = "AI-powered security analysis using LangChain and GitHub Advanced Security"
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.3.18"
langgraph = "^0.2.73"
openai = "^1.3.0"
pygithub = "^2.1.1"

[tool.poetry.dev-dependencies]
pytest = "^7.4.0"
pytest-asyncio = "^0.21.1"
black = "^23.7.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
